from langchain_core.messages import  HumanMessage, AIMessage, ToolMessage
StateSnapshot(
    values={'messages': 
            [
                HumanMessage(content='Can you book a flight for me to "JAIPUR" on "25/01/2025"?', additional_kwargs={}, response_metadata={}, id='cf9ef75c-e871-4267-a517-d8bc7ed417ef'), 
                AIMessage(content='', additional_kwargs={'tool_calls': [{'id': 'call_Qhj4w9aP3ht5jWdyPNWyLuZe', 'function': {'arguments': '{"user_id":3,"location":"JAIPUR","request":"Please book a flight for me to Jaipur on 25/01/2025."}', 'name': 'ToTravelAssistant'}, 'type': 'function'}], 'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 43, 'prompt_tokens': 1446, 'total_tokens': 1489, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_72ed7ab54c', 'finish_reason': 'tool_calls', 'logprobs': None}, id='run-3ef9feb7-dd35-4f29-aa0f-6e5628b52897-0', tool_calls=[{'name': 'ToTravelAssistant', 'args': {'user_id': 3, 'location': 'JAIPUR', 'request': 'Please book a flight for me to Jaipur on 25/01/2025.'}, 'id': 'call_Qhj4w9aP3ht5jWdyPNWyLuZe', 'type': 'tool_call'}], usage_metadata={'input_tokens': 1446, 'output_tokens': 43, 'total_tokens': 1489, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}}), 
                ToolMessage(content="The assistant is now the Travel management Assistant. Reflect on the above conversation between the host assistant and the user. The user's intent is unsatisfied. Use the provided tools to assist the user. Remember, you are Travel management Assistant, and the booking, update, other other action is not complete until after you have successfully invoked the appropriate tool. If the user changes their mind or needs help for other tasks, call the CompleteOrEscalate function to let the primary host assistant take control. Do not mention who you are - just act as the proxy for the assistant.", id='596cbc54-106c-402c-b55e-cc1ad6c3062b', tool_call_id='call_Qhj4w9aP3ht5jWdyPNWyLuZe'), 
                AIMessage(content='Could you please provide me with the following details to book your flight to Jaipur on 25/01/2025?\n\n1. Your starting location (source).\n2. Mode of transport (e.g., flight, train, bus).\n3. Traveler details (e.g., name, age, passport details).\n\nOnce I have these details, I can proceed with the booking!', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 77, 'prompt_tokens': 1788, 'total_tokens': 1865, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_72ed7ab54c', 'finish_reason': 'stop', 'logprobs': None}, id='run-87ef60b7-c60c-4384-bbb2-5d195fbd5b05-0', usage_metadata={'input_tokens': 1788, 'output_tokens': 77, 'total_tokens': 1865, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}}), 
                HumanMessage(content='delhi \nvia flight\nmy name is siddhesh 24\nand what passport details you need', additional_kwargs={}, response_metadata={}, id='459e5dbb-5d19-458b-9cfc-78741b473bc0'), 
                AIMessage(content='I just need the passport number and expiration date for the booking. Could you please provide me with those details?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 24, 'prompt_tokens': 1892, 'total_tokens': 1916, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_72ed7ab54c', 'finish_reason': 'stop', 'logprobs': None}, id='run-755c956a-2ead-487c-abb3-fe2745ce24c9-0', usage_metadata={'input_tokens': 1892, 'output_tokens': 24, 'total_tokens': 1916, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}}), 
                HumanMessage(content='ohhh ok 43335566464 12/25', additional_kwargs={}, response_metadata={}, id='43fe64b7-1e80-4bd5-8de8-9e5288b51d02'), 
                AIMessage(content='', additional_kwargs={'tool_calls': [{'id': 'call_h6jvAuLpp9wTeinIYC7CIOhl', 'function': {'arguments': '{"user_id":1,"travel_date":"2025-01-25","source":"Delhi","destination":"Jaipur","mode_of_transport":"flight","traveler_details":[{"name":"siddhesh","age":24,"passport_details":{"passport_number":"43335566464","expiration_date":"12/25"}}]}', 'name': 'book_ticket'}, 'type': 'function'}], 'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 76, 'prompt_tokens': 1934, 'total_tokens': 2010, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_72ed7ab54c', 'finish_reason': 'tool_calls', 'logprobs': None}, id='run-9b09cbc3-0151-45df-8fa5-359363e3a9d0-0', tool_calls=[{'name': 'book_ticket', 'args': {'user_id': 1, 'travel_date': '2025-01-25', 'source': 'Delhi', 'destination': 'Jaipur', 'mode_of_transport': 'flight', 'traveler_details': [{'name': 'siddhesh', 'age': 24, 'passport_details': {'passport_number': '43335566464', 'expiration_date': '12/25'}}]}, 'id': 'call_h6jvAuLpp9wTeinIYC7CIOhl', 'type': 'tool_call'}], usage_metadata={'input_tokens': 1934, 'output_tokens': 76, 'total_tokens': 2010, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}}), 
                ToolMessage(content='1001', name='book_ticket', id='2eef5874-7dd3-4144-b2d8-afd381a79281', tool_call_id='call_h6jvAuLpp9wTeinIYC7CIOhl'), 
                AIMessage(content='Your flight from Delhi to Jaipur on 25/01/2025 has been successfully booked. Your ticket ID is **1001**. \n\nIf you need any further assistance or would like to set up notifications for your booking, just let me know!', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 53, 'prompt_tokens': 2019, 'total_tokens': 2072, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_72ed7ab54c', 'finish_reason': 'stop', 'logprobs': None}, id='run-8a22d14d-7388-4b54-aaa3-b2fbc609f1f1-0', usage_metadata={'input_tokens': 2019, 'output_tokens': 53, 'total_tokens': 2072, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}}), 
                HumanMessage(content='I need to cancel my flight ticket for "JAIPUR". Can you do that?', additional_kwargs={}, response_metadata={}, id='6e2329a3-eda8-4bc5-98c1-69216afd68f7'), 
                AIMessage(content="Please provide me with your user ID and the ticket ID for the flight to Jaipur that you want to cancel. If you don't have the ticket ID, I can look it up for you based on your previous booking.", additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 45, 'prompt_tokens': 2096, 'total_tokens': 2141, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_72ed7ab54c', 'finish_reason': 'stop', 'logprobs': None}, id='run-23511822-7c3a-4b5e-af7c-011c96500d1e-0', usage_metadata={'input_tokens': 2096, 'output_tokens': 45, 'total_tokens': 2141, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}}), 
                HumanMessage(content='please use my user id ', additional_kwargs={}, response_metadata={}, id='d2777874-4dc2-4b3d-9f87-2773c1f46e84'), 
                AIMessage(content='', additional_kwargs={'tool_calls': [{'id': 'call_LCEdFByBGKgsMOXFzm9tdFdG', 'function': {'arguments': '{"user_id":1,"ticket_id":1001}', 'name': 'cancel_ticket'}, 'type': 'function'}], 'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 22, 'prompt_tokens': 2153, 'total_tokens': 2175, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_72ed7ab54c', 'finish_reason': 'tool_calls', 'logprobs': None}, id='run-d313cb95-298c-428a-91a8-2471aceb96c0-0', tool_calls=[{'name': 'cancel_ticket', 'args': {'user_id': 1, 'ticket_id': 1001}, 'id': 'call_LCEdFByBGKgsMOXFzm9tdFdG', 'type': 'tool_call'}], usage_metadata={'input_tokens': 2153, 'output_tokens': 22, 'total_tokens': 2175, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})], 'user_info': {'user_id': '3', 'user_name': 'John Doe', 'user_type': 'DEV_TESTER'}, 'dialog_state': ['ASSISTANT_TRAVEL']}, 
    next=('TRAVEL_SENSITIVE_TOOLS',), 
    config={'configurable': {'thread_id': '0bb90c65-483c-4f42-a761-df3267be529a', 'checkpoint_ns': '', 'checkpoint_id': '1efd7a19-3d4f-6c30-8016-8d921b7f5cd1'}}, 
    metadata={
        'source': 'loop', 
        'writes': {'ASSISTANT_TRAVEL': 
                   {'messages': 
                    AIMessage(
                        content='', 
                        additional_kwargs={'tool_calls': [{'id': 'call_LCEdFByBGKgsMOXFzm9tdFdG', 'function': {'arguments': '{"user_id":1,"ticket_id":1001}', 'name': 'cancel_ticket'}, 'type': 'function'}], 'refusal': None}, 
                        response_metadata={'token_usage': {'completion_tokens': 22, 'prompt_tokens': 2153, 'total_tokens': 2175, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_72ed7ab54c', 'finish_reason': 'tool_calls', 'logprobs': None}, 
                        id='run-d313cb95-298c-428a-91a8-2471aceb96c0-0', 
                        tool_calls=[{'name': 'cancel_ticket', 'args': {'user_id': 1, 'ticket_id': 1001}, 'id': 'call_LCEdFByBGKgsMOXFzm9tdFdG', 'type': 'tool_call'}], 
                        usage_metadata={'input_tokens': 2153, 'output_tokens': 22, 'total_tokens': 2175, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}}
                    )
                   }
                }, 
        'user_id': '3', 
        'thread_id': '0bb90c65-483c-4f42-a761-df3267be529a', 
        'step': 22, 
        'parents': {}
    }, 
    created_at='2025-01-21T02:44:04.169016+00:00', 
    parent_config={'configurable': {'thread_id': '0bb90c65-483c-4f42-a761-df3267be529a', 'checkpoint_ns': '', 'checkpoint_id': '1efd7a19-309f-6587-8015-95da3af7002f'}}, 
    
    tasks=(
        PregelTask(
            id='b9ad6578-1d0a-e6b2-8675-669695ba9b47', 
            name='TRAVEL_SENSITIVE_TOOLS', 
            path=('__pregel_pull', 'TRAVEL_SENSITIVE_TOOLS'), 
            error=None, 
            interrupts=(), 
            state=None, 
            result=None
        ),
    )
)
